<?
	/*
	 * LANsurfer - Beamer Module
	 */

	$info['setup'] = array(							// Setup options
		'LS_BEAMER_MSGNO' => array('caption' => _("Beamer news items"), 'default' => '3'), 
		'LS_BEAMER_SPONSORS' => array('caption' => _("Beamer sponsors"), 'default' => "<CENTER>\n<FONT FACE=\"Verdana\" COLOR=\"#99CCFF\" SIZE=\"5\"><B>Insert sponsors here ...</B></FONT>\n</CENTER>", 'type' => 'textarea'), 
	);
	
	$info['sql'] = array(								// SQL Tables
	);
	
?>