<?
	$LS_BASEPATH = "../";
	include $LS_BASEPATH."../includes/ls_base.inc";

	$res = SQL_Query("SELECT forum_topic.title
		FROM forum_topic
		WHERE (forum_topic.id=$id)");
	$TopicInfo = mysql_fetch_array($res);
	NavAdd("Forum", "index.phtml");

	$LS_OPENPAGE = TRUE;
	
	StartPage($TopicInfo[title]);

	$ForumAdmin = user_auth_ex(AUTH_TEAM, 0, TEAM_FORUM, FALSE);
	
	if ($user_valid && ($PageSize = $user_current[forum_pagecount]) > 25) {

	} else
		$PageSize = 25;

	$PageCount = 0;
	

	function make_clickable($text)
	{
    $ret = eregi_replace("[^=](http|ftp|https)://([^[:space:]]*)([[:alnum:]#?/&=])", " <a href=\"\\1://\\2\\3\" target=\"_blank\" target=\"_new\">\\1://\\2\\3</a>", $text);
//    $ret = eregi_replace("[^=]?(([a-z0-9_]|\\-|\\.)+@([^[:space:]]*)([[:alnum:]-]))]", "<a href=\"mailto:\\1\" target=\"_new\">\\1</a>", $ret);

//    $ret = eregi_replace("([[:alnum:]]+)://([^[:space:]]*)([[:alnum:]#?/&=])", "<a href=\"\\1://\\2\\3\" target=\"_blank\" target=\"_new\">\\1://\\2\\3</a>", $text);
//    $ret = eregi_replace("(([a-z0-9_]|\\-|\\.)+@([^[:space:]]*)([[:alnum:]-]))", "<a href=\"mailto:\\1\" target=\"_new\">\\1</a>", $ret);
    return($ret);
	}
	
	function UBB2HTML($text) {
		$codes = array("b", "i", "u");

		$text = make_clickable($text);

		
		for ($i = 0; $i < count($codes); $i++) {
			$ch = $codes[$i];
			$text = str_replace ("[$ch]", "<$ch>", $text);
			$text = str_replace ("[/$ch]", "</$ch>", $text);
		}
		
		$text = eregi_replace("\\[url\\=([[:alnum:]:@._/#?&=-]+)\\]([^\\[]*)\\[/url\\]", "<a href=\"\\1\" target=\"_new\">\\2</a>",$text);
//		$text = eregi_replace("\\[img\\=([[:alnum:]:@._/#?&=]+)\\]", "<img src=\"\\1\">",$text);


		return $text;
	}


	?>
	<p>
	<?
		$res = SQL_Query("SELECT COUNT(*) AS 'cnt' FROM forum_posting WHERE (topic=$id)");
		$row = mysql_fetch_array($res);
		$PageCount = ceil($row[cnt] / $PageSize);
		
		if (!isset($page))
			$page = $PageCount - 1;
		
		if ($PageCount > 1) {
			echo "Das Thema ist $PageCount Seiten lang:";
			for ($i = 0; $i < $PageCount; $i++) {
				echo " ";
				if ($i == $page)
					echo $i + 1;
				else
					echo "<a href=\"$PHP_SELF?id=$id&page=$i\">".($i + 1)."</a>";
			}
			echo "<br><br>";
		}
	?>
	<? NavPrintAction("topic.phtml?action=reply&forum=".$TopicInfo[id]."&topic=$id", "Antwort erstellen"); ?><br>
	<br>
	<div align="center">
	<table class="liste" width="96%"> <!--  -->
		<tr class="liste">
			<th class="liste" width=160>Autor</th>
			<th class="liste">Thema: <? echo $TopicInfo[title]; ?></th>
		<tr>
	<?
		flush();
	
		$res = SQL_Query("SELECT 
			fp.id,
			fp.text, 
			DATE_FORMAT(fp.date, '%d.%m.%Y') as 'date',
			DATE_FORMAT(fp.date, '%H:%i') as 'time',
			TO_DAYS(CURDATE()) - TO_DAYS(fp.date) as 'past',
			fp.ls_id,
			user.name as 'username',
			user.id as 'userid',
			user.clan,
			fp.name,
			fp.email
			
			FROM forum_posting AS fp LEFT JOIN user ON (user.id=fp.ls_id)
			WHERE (topic=$id)
			ORDER BY fp.date
			LIMIT ".($page * $PageSize).",$PageSize");
		while ($row = mysql_fetch_array($res)) {
		?>
		<tr class="liste">
			<td class="liste" valign="top">
				Von:<br>
				<?
					if ($row[ls_id] > 0) {
						echo $row[username];
						if ($row[clan]) {
							echo "<br>Clan:<br>";
							echo $row[clan];
						}
						
					} else {
						echo "<a href=\"mailto:".$row[email]."\">".HTMLStr($row[name])."</a>";
					}
				
				?><br>
				<br>
				Datum:<br>
				<? 
					switch ($row[past]) {
						case 0:
							echo "<b>Heute</b>";
							break;
						case 1:
							echo "<b>Gestern</b>";
							break;
						default:
							echo $row[date];
					}
				  echo ", ".$row[time]; 
				echo "<br>";
				if ($user_current[id] == $row[userid])
					echo "<br><a href=\"topic.phtml?action=edit&id=".$row[id]."\">Bearbeiten</a>";
				if ($ForumAdmin)
					printf("<br><a href=\"topic.phtml?action=removepost&id=%d\">Entfernen</a>", $row[id]);
				 ?>
			</td>
			<td class="liste" valign="top"><? 
				$htmltext= UBB2HTML(nl2br(htmlspecialchars($row[text])));
				
			
//				echo make_clickable(); 
				echo $htmltext;
			?></td>
		</tr>
		<?
		}
	?>		
	<tr>
		<td align="left" class="content"><? 
			if ($page > 0 && $PageCount)
				NavPrintPrevPage($PHP_SELF."?id=$id&page=".($page - 1));
		?></td>
		<td align="right" class="content"><?
			if ($page < ($PageCount - 1))
				NavPrintNextPage($PHP_SELF."?id=$id&page=".($page + 1));
		?></td>
	</tr>
	</table>
	</div>
	<br>
	
	<? NavPrintAction("topic.phtml?action=reply&forum=".$TopicInfo[id]."&topic=$id", "Antwort erstellen"); ?>

	</p>
	<?
	
	NavPrintBack();

	EndPage();
?>
