<?
	$LS_BASEPATH = "../";
	include $LS_BASEPATH."../includes/ls_base.inc";

	if ($action == "edit" || $action == "removepost") {
		$res = SQL_Query("SELECT * FROM forum_posting WHERE id=$id");
		$Post = mysql_fetch_array($res);
		
		$topic = $Post[topic];
		$res = SQL_Query("SELECT * FROM forum_topic WHERE id=$topic");
		$Topic = mysql_fetch_array($res);
		$forum = $Topic[forum];
	} elseif ($action == "remove") {
		$topic = $id;
		$res = SQL_Query("SELECT * FROM forum_topic WHERE id=$id");
		$Topic = mysql_fetch_array($res);
		$forum = $Topic[forum];
	}
	
	NavAdd("Forum", "index.phtml");
	
	if ($action == "reply" || $action == "edit" || $action == "removepost") {
		switch ($action) {
				case "edit":
					$PageTitle = "Beitrag Bearbeiten";
					break;
				case "reply":
					$PageTitle = "Antwort Erstellen";
					break;
				case "removepost":
					$PageTitle = "Beitrag Entfernen";
					break;
		}
		$res = SQL_Query("SELECT * FROM forum_topic WHERE (id=$topic)");
		$TopicInfo = mysql_fetch_array($res);
		NavAdd($TopicInfo[title], "postings.phtml?id=".$TopicInfo[id]);
		
	} elseif ($action == "remove") {
		$PageTitle = "Thema Entfernen";
	} else {
		$PageTitle = "Neues Thema";
	}
	
	$LS_OPENPAGE = TRUE;
	
	StartPage($PageTitle);

	$ForumAdmin = user_auth_ex(AUTH_TEAM, 0, TEAM_FORUM, FALSE);

	if ($action == "edit" && $Post[ls_id] != $user_current[id] && !$ForumAdmin)
		LS_Error("Ung&uuml;ltiger Benzutzer.");
	
	if ($action == "new" || $action == "edit" || $action == "reply") {
		
		if ($action == "edit" && $user_current[id] != $Post[ls_id]) {
			if (!$Post[ls_id])
				$PostingUserName = $Post[name];
			else {
				$res = SQL_Query("SELECT name FROM user WHERE id=".$Post[ls_id]);
				$PostUser = mysql_fetch_array($res);
				$PostingUserName = $PostUser[name];
			}
		}
		
		FormStart();
		if ($submited) {
			if ($f_title == "" && $action == "new")
				FormError("f_title", "Der Titel darf nicht leer sein");
			if ($action != "edit" && !$f_ls_id) {
				if ($f_name == "")
					FormError("f_name", "Du musst einen Namen angeben oder dich vorher einloggen");
			}
			if ($f_text == "")
				FormError("f_text", "Dein Beitrag sollte schon einen Text enthalten");
				
			
			
			if (!$FormErrorCount) {
				if (isset($f_ls_id) && ($f_ls_id > 0))
					$userfields = ",ls_id=$f_ls_id";
				else
					$userfields = ", name='".SQL_Str($f_name)."', email='".SQL_Str($f_email)."'";

				if ($action == "new") {
					SQL_Query("INSERT INTO forum_topic SET title='".SQL_Str($f_title)."', pcount=1");
					$topicid="LAST_INSERT_ID()";
					
				} elseif ($action != "edit") {
					$topicid = $topic;
					
					SQL_Query("UPDATE forum_posting SET flags=0 WHERE (topic=$topicid)");

					$res = SQL_Query("SELECT COUNT(*) FROM forum_posting WHERE (topic=$topic)");
					$cnt = mysql_result($res, 0, 0);
					$cnt++;
					SQL_Query("UPDATE forum_topic SET pcount=$cnt WHERE (id=$topic)");
				}
				
				
				if ($action == "edit") {
					$f_text = $f_text."\n\n[i](Dieser Beitrag wurde am ".date("d.m.Y")." um ".date("H:i")." bearbeitet.)[/i]\n";
				
					SQL_Query("UPDATE forum_posting SET text='".SQL_Str($f_text)."' WHERE id=$id");
					echo "Die &Auml;nderungen wurden gespeichert.<br>";
				}
				else {
					if ($user_valid && $user_current[forum_signature] && !$f_hide_signature) {
						$f_text .= "\n\n".$user_current[forum_signature];
					}

					$fields = "topic=$topicid,text='".SQL_Str($f_text)."', flags=1, date=NOW()";
				
					SQL_Query("INSERT INTO forum_posting SET ".$fields.$userfields);
					echo "Dein Betrag wurde aufgenommen.<br>";
				}
				
			}
		} else {
			if ($action == "edit") {
				$f_text = $Post[text];
			}
		}
	
		if (!$submited || $FormErrorCount) {
			FormValue("submited", 1);
			FormValue("action", $action);
			FormValue("forum", $forum);
			FormValue("id", $id);
			FormValue("topic", $topic);
			
			if ($PostingUserName)
				FormVisibleValue("Name", HTMLStr($PostingUserName));
			elseif ($user_valid) {
				FormVisibleValue("Name", HTMLStr($user_current[name]));
				FormVisibleValue("Email", HTMLStr($user_current[email]));
				if ($action != "edit" && $user_current[forum_signature])
					FormElement("f_hide_signature", "Signatur nicht verwenden", 1, "checkbox");
				FormValue("f_ls_id", $user_current[id]);
			} else {
				FormElement("f_name", "Dein Name", $f_name);
				FormElement("f_email", "Deine Email Addresse", $f_email);
			}
			if ($action == "new")
				FormElement("f_title", "Titel", $f_title, "text", "size=30");
			FormElement("f_text", "Text", $f_text, "textarea", "cols=70 rows=20");
			
			
			FormElement("", "", ($action == "edit") ? "Speichern" : "Erstellen", "submit");
		}

		FormEnd();

		if (!$submited || $FormErrorCount) {
?>
	<p class="contentpanel">
	HTML Code ist nicht erlaubt.<br>
	Folgende Dinge kann man jedoch zur Formatierung verwenden:<br>
	<ul>
		<li>[b]Text[/b] f&uuml;r <b>fetten</b> Text</li>
		<li>[i]Text[/i] f&uuml;r <i>kursiven</i> Text</li>
		<li>[u]Text[/u] f&uuml;r <u>unterstrichenen</u> Text</li>
		<li>[url=http://www.url.de]Titel der URL[/url] um einen Link mit Titel darzustellen. Normale URLs werden automatisch in Links umgewandelt</li>
	</ul>
	</p>
<?
		}
		
	} elseif ($action == "remove") {
		user_auth_ex(AUTH_TEAM, 0, TEAM_FORUM);


		if ($submited) {	
			SQL_Query("DELETE FROM forum_posting WHERE topic=$id");
			SQL_Query("DELETE FROM forum_topic WHERE id=$id");
			printf("<p class=\"content\">Das Thema <i>%i</i> wurde entfernt.</p>", $Topic[title]);
		} else {
			printf("<p class=\"content\">Bist du sicher das du das <b>gesamte</b> Thema <i>%s</i> <b>entfernen</b> willst?</p>", $Topic[title]);
			
			FormStart();
				FormValue("action", $action);
				FormValue("id", $id);
				FormValue("submited", 1);
				FormElement("", "", "Entfernen", "submit");
			FormEnd();
		}
	} elseif ($action == "removepost") {
		user_auth_ex(AUTH_TEAM, 0, TEAM_FORUM);


		if ($submited) {
			SQL_Query("DELETE FROM forum_posting WHERE id=$id");
			if ($Post[flags] & 1) {  	// remove last posting
				$res = SQL_Query("SELECT id FROM forum_posting WHERE (topic=".$Post[topic].") ORDER BY date DESC LIMIT 1");
				$LastPost = mysql_fetch_array($res);
				$res = SQL_Query("UPDATE forum_posting SET flags=1 WHERE id=".$LastPost[id]);
			}
			$res = SQL_Query("SELECT COUNT(*) FROM forum_posting WHERE (topic=".$Post[topic].")");
			$cnt = mysql_result($res, 0, 0);
			SQL_Query("UPDATE forum_topic SET pcount=$cnt WHERE id=".$Post[topic]);

			printf("<p class=\"content\">Der Beitrag wurde entfernt.</p>");
		} else {
			printf("<p class=\"content\">Bist du sicher das du den Beitrag <b>entfernen</b> willst?</p>");
			
			FormStart();
				FormValue("action", $action);
				FormValue("id", $id);
				FormValue("submited", 1);
				FormElement("", "", "Entfernen", "submit");
			FormEnd();
		}
	}
	
	NavPrintBack();

	EndPage();
?>