<?
	$LS_BASEPATH = "../";
	include $LS_BASEPATH."../includes/ls_base.inc";

	function PrintDel($url, $caption = "L&ouml;schen") {
		echo "<a href=\"$url\" class=\"action_del\" title=\"$caption\">&nbsp;X&nbsp;</a>";
	}
	
	StartPage("Orga Team");
	
	user_auth_ex(AUTH_TEAM);
	
?>
	<h3 class="contentpanel">G&auml;ste</h3>
	<?
		NavPrintAction("guests.phtml", "G&auml;steliste");
		echo "<br>";
		NavPrintAction("new_guest.phtml", "Neuen Benutzer/Gast");
		echo "<br>";
		NavPrintAction("guest_stat.phtml", "Stand der Dinge");
		echo "<br>";
		NavPrintAction("ip_adder.phtml", "IP-Vergabe");
		echo "<br>";

		$news_status = 0;
		if (user_auth_ex(AUTH_TEAM, $id, TEAM_NEWS, FALSE))
			$news_status = 1;
		if (user_auth_ex(AUTH_TEAM, $id, TEAM_NEWS_ALL, FALSE))
			$news_status = 2;
	
	?>

	<? if ($news_status): ?>

	<h3 class="contentpanel">Neuigkeiten</h3>
	<p>
		<? NavPrintAction("news.phtml?action=new&team=".$team[id], "Neue Meldung") ?><br>
		<br>
		<?
			$header = FALSE;
			$res = SQL_Query("SELECT *, 
				DATE_FORMAT(news.date, '%e.%m.%Y') as 'disp_date',
				news.id as 'news_id'
				FROM news LEFT JOIN user ON author=user.id
				ORDER BY news.date DESC");
			while ($row = mysql_fetch_array($res)) {
				if (!$header) {
					$header = TRUE;
					?>
				<table class="liste">
					<tr>
						<th class="liste" width="180">Titel</th>
						<th class="liste" width="80">Datum</th>
						<th class="liste" width="100">Author</th>
					</tr>
					<?
				}
				
				?>
				<tr class="liste">
					<td class="liste"><? 
					$not_own_post = $news_status != 2 && $row[author] != $user_current[id];
					if ($not_own_post)
						echo $row[title];
					else
						echo "<a href=\"news.phtml?action=edit&team=$id&id=".$row[news_id]."\">".$row[title]."</a>"; 
					
					?></td>
					<td class="liste" align="right"><? echo $row[disp_date]; ?></td>
					<td class="liste"><? echo $row[name]; ?></td>
					<td><? 
						if (!$not_own_post)
							PrintDel("news.phtml?action=remove&team=$id&id=".$row[news_id]); 
					?></td>
				</tr>
				<?
			}
			if ($header) {
			?>
			</table>
			<?
			}
		?>
	</p>
	
	<? endif; ?>

	<!-- Member -->
	<?
		$member_readonly = !user_auth_ex(AUTH_TEAM, $id, TEAM_USER, FALSE);
	
	?>

	<h3 class="contentpanel">Mitglieder</h3>
	<p>
		<? if (!$member_readonly): ?>
		<? NavPrintAction("team.phtml?action=neworga&team=$id", "Neues Mitglied") ?><br>
		<br>
		<? endif; ?>
		<table class="liste">
			<tr class="liste">
				<th width="180" class="liste">Name</th>
				<th width="80" class="liste">Rechte</th>
			</tr>
		<?
			function PrintRight($right, $letter, $title = "") {
				global $row;
				
				if ($title)
					echo "<span title=\"$title\">";
				echo ($row[rights] & $right) ? $letter : "-";
				if ($title)
					echo "</span>";
			}
		
			$res = SQL_Query("SELECT 
				orga.id,
				user.email, 
				user.name,
				orga.rights 
				FROM orga LEFT JOIN user ON user=user.id");
			
			while ($row = mysql_fetch_array($res)) {
		?>
			<tr class="liste">
				<td class="liste">
					<? if ($member_readonly): ?>
					<? echo $row[name]; ?>
					<? else: ?>
					<a href="member.phtml?action=edit&id=<? echo $row[id]; ?>"><? echo $row[name]; ?>
					<? endif; ?>
				
				</td>
				<td class="liste"><font face="Courier New" size=2><? 
				// echo $row[rights]; 
					PrintRight(TEAM_USER,		"U", "Benutzer hinzuf&uuml;gen/entfernen/Rechte &auml;ndern");
					PrintRight(TEAM_PARTY,	"P", "Parties anlegen/&auml;ndern");
					PrintRight(TEAM_GUEST,	"G", "G&auml;ste auf bezahlt setzen / l&ouml;schen");
					PrintRight(TEAM_NEWS,		"n", "News posten und eigene news bearbeiten/l&ouml;schen");
					PrintRight(TEAM_NEWS_ALL, "N", "Alle News bearbeiten/l&ouml;schen ");
					PrintRight(TEAM_DESIGN,	"D", "Designs Anlegen/l&ouml;schen/bearbeiten");
					PrintRight(TEAM_FORUM,	"F", "Foren Anlegen/l&ouml;schen/bearbeiten");
					PrintRight(TEAM_TOURNEY,"T", "Turniere Anlegen/l&ouml;schen/bearbeiten");
				?></font></td>
				<td><? 
					if (!$member_readonly)
						PrintDel("team.phtml?action=remove&id=".$row[id], "Entfernen"); 
					?></td>
			</tr>
		<?
			}
		?>	
		</table>
	</p>

	<? /* if (user_auth_ex(AUTH_TEAM, $id, TEAM_DESIGN, FALSE)): ?>
	<!-- Design  -->

	<h3 class="contentpanel">Design</h3>
	<p>
		<? if (user_auth_ex(AUTH_LS_INTERN, 0, 0, false)): ?>
		<? NavPrintAction("design.phtml?action=new&team=$id", "Neues Design"); ?><br>
		<br>
		<? endif; ?>
	
		<table class="liste">
			<tr class="liste">
				<th class="liste" width=260>Name</th>
			</tr>
			<?
				$res = SQL_Query("SELECT * FROM design WHERE (team=0) OR (team=$id)");
				while ($row = mysql_fetch_array($res)) {
				?>
				<tr class="liste">
					<td class="liste" width=180><a href="design.phtml?team=<? echo $id; ?>&id=<? echo $row[id]; ?>"><? echo $row[name]; ?></a></td>
					<td><? PrintDel("design.phtml?action=remove&team=$id&id=".$row[id]); ?></td>
				</tr>					
				<?
				}
			?>
		</table>
	</p>
	
	<? endif; */?>

	<? /* if (user_auth_ex(AUTH_TEAM, $id, TEAM_FORUM, FALSE)): ?>
	<h3 class="contentpanel">Foren</h3>
	<p>
		<? NavPrintAction("forum.phtml?action=new&team=$id", "Neues Forum"); ?><br>
		<br>
		<?
			$header = FALSE;
			$res = SQL_Query("SELECT * FROM forum WHERE (team=$id) ORDER BY name");
			while ($row = mysql_fetch_array($res)) {
				if (!$header) {
					$header = TRUE;
				?>
				<table class="liste">
				<tr class="liste">
					<th class="liste">Name</th>
					<th class="liste">Themen</th>
					<th class="liste">Ansicht</th>
				</tr>
				<?
				}	
				?>
				<tr class="liste">
					<td class="liste" width=180><a href="forum.phtml?team=<? echo $id; ?>&id=<? echo $row[id]; ?>"><? echo $row[name]; ?></a></td>
					<td class="liste">(Unbekannt)</td>
					<td class="liste"><a href="<? echo $LS_BASEPATH; ?>forum/show.phtml?id=<? echo $row[id]; ?>">Anzeigen</a></td>
					<td><? PrintDel("forum.phtml?action=remove&team=$id&id=".$row[id]); ?></td>
				</tr>					
				<?
			}
			if ($header)
				echo "</table>";
		?>
	</p>
	<? endif; */ ?>
	<?
	
	EndPage();

?>