<?
	$LS_BASEPATH = "../";
	include $LS_BASEPATH."../includes/ls_base.inc";

	$res = SQL_Query("SELECT user.id, user.name, orga.rights FROM orga LEFT JOIN user ON orga.user=user.id WHERE orga.id=$id");
	$OrgaInfo =mysql_fetch_array($res);

	NavAdd("Orga Team", $LS_BASEPATH."orga/");
	
	StartPage("Mitglieder");
	
	if ($action == "edit") {
		
		user_auth_ex(AUTH_TEAM);
		
		function FormRightCheck($right, $caption) {
			global $f_right, $OrgaInfo;
		
			FormElement("f_right[".$right."]", $caption, 1, "checkbox", ($OrgaInfo[rights] & $right) ? "checked" : "");
		}
		
		if ($submited) {
			$newrights = 0;

			reset ($f_right);
			while (list($key, $value) = each ($f_right)) {
				if ($f_right[$key])
					$newrights |= $key;
  		}
  		SQL_Query("UPDATE orga SET rights=$newrights WHERE id=$id");
  		echo "<p>Die &Auml;nderungen wurden gespeichert.</p>";
  		
  		NavPrintBack();
  
		} else {
			?><h3 class=contentpanel>Mitglieder</h3><?
			
			echo "<b>Name: </b>".$OrgaInfo[name]."<br><br>";

			FormStart("action=\"$PHP_SELF\" method=\"post\"");
				FormValue("action", $action);
				FormValue("submited", 1);
				FormValue("team", $team);
				FormValue("id", $id);
				
				FormGroup("Rechte im Team");
				
				FormRightCheck(TEAM_USER,			"Mitglieder hinzuf&uuml;gen/ver&auml;ndern/l&ouml;schen");
				FormRightCheck(TEAM_PARTY,		"Parties anlegen/ver&auml;ndern/l&ouml;schen");
				FormRightCheck(TEAM_GUEST,		"G&auml;ste als bezahlt markieren und/oder G&auml;ste l&ouml;schen");
				FormRightCheck(TEAM_NEWS,			"Neuigkeiten verfassen/&auml;ndern/l&ouml;schen");
				FormRightCheck(TEAM_NEWS_ALL,	"Neuigkeiten von Anderen Team mitgliedern verfassen/&auml;ndern/l&ouml;schen");
				FormRightCheck(TEAM_DESIGN,		"Designs anlegen/ver&auml;ndern/l&ouml;schen");
				FormRightCheck(TEAM_FORUM,		"Foren anlegen/ver&auml;ndern/l&ouml;schen");
				FormRightCheck(TEAM_TOURNEY,	"Tourney anlegen/ver&auml;ndern/l&ouml;schen");
				
				
				FormElement("", "", "&Auml;nderungen Speichern", "submit");
			FormEnd();
		}
	}


	EndPage();
	
?>