<head>
	<title>Setup</title>
	<style>
	<!--
	BODY {
		FONT-FAMILY: Verdana, Helvetica;
		FONT-SIZE: 12px;
	}
	
	TH.liste {
		FONT-FAMILY: Verdana,Helvetica;
		FONT-SIZE: 12px;
		FONT-WEIGHT: normal;
    BACKGROUND-COLOR: #333333;
    COLOR: WHITE;
	}
	
	TD.liste {
		FONT-FAMILY: Verdana,Helvetica;
		FONT-SIZE: 12px;
		FONT-WEIGHT: normal;
	  BACKGROUND-COLOR: #555555;
	  COLOR: WHITE;
	}
	
	H2 {
		FONT-FAMILY: Verdana,Helvetica;
		FONT-SIZE: 24px;
		FONT-WEIGHT: bold;
	}
	-->
	</style>
</head>
<body>
<h2>LANsurfer Intranet Setup</h2>
<p class=content>
<b>Hinweis:</b> Diese Datei <i>_setup.phtml</i> sollte nach erfolgreicher Konfiguration und Import umbenannt und oder ausserhalb des von Browsern zu erreichenden Verzeichnisses liegen.
</p>
<p class=content>
PHP Lauffähig: <!--
<?
	echo ' -'.'-'.'> <b>Ja</b>';	
	
	echo '</p><p class=content>';
	
	$LS_BASEPATH = "";
	include $LS_BASEPATH."../includes/ls_base.inc";
?>
<b>SQL Konfiguration:</b><br>
<?
	
  if (TRUE)
  {
  	?>
  	<table>
  		<tr class=liste>
  			<th class=liste width=80>Server</th>
  			<td class=liste width=200><? echo SQL_HOST; ?></td>
  		</tr>
  		<tr class=liste>
  			<th class=liste>Datenbank</th>
  			<td class=liste><? echo SQL_DB; ?></td>
  		</tr>
  		<tr class=liste>
  			<th class=liste>Benutzer</th>
  			<td class=liste><? echo SQL_USER; ?></td>
  		</tr>
  		<tr class=liste>
  			<th class=liste>Passwort</th>
  			<td class=liste><? echo (SQL_PASSWORD) ? "Gesetzt" : "nicht gesetzt"; ?></td>
  		</tr>
  	</table>
  	<?
  } else {
  	LS_Error("Die SQL Configuration wurde noch <b>nicht</b> vorgenommen. Bitte &uuml;berpr&uuml;fe die Angaben in der <i>includes/ls_conf.inc</i> Datei");
  }
?>
</p>
<p class=content>
<b>Tabellen:</b><br>
<ul>
<?  
	SQL_Init(false);
  echo "<li>Suche nach Datenbanken...";
  $res = mysql_Query("show databases");
  while ($row = mysql_fetch_row($res)) {
  	$databases[$row[0]] = TRUE;
  }
  echo "OK</li><br><li>";
  if ($databases[SQL_DB])
  	printf("Datenbank %s existiert.", SQL_DB);
  else {
  	printf("Die Datenbank %s wird angelegt ... ", SQL_DB);
  	SQL_Query("CREATE DATABASE ".SQL_DB);
  	echo "OK.";
  }
  echo "</li>";

	mysql_select_db(SQL_DB);
	
  echo "<li>Suche nach vorhandene Tabellen in der Datenbank...";
  $res = SQL_Query("show tables;");
  while ($row = mysql_fetch_row($res)) {
  	$tables[$row[0]] = TRUE;
  }
  echo "OK</li><br>";

?>
<li>Anlegen der ben&ouml;tigten Tabellen:<br>
<table>
	<tr>
		<th class=liste width=200>Tabelle</th>
		<th class=liste width=200>Status</th>
	</tr>
<?

   function CreateTable($table, $fields) {
   		global $tables;
   		echo "<tr>";
   		printf("<td class=liste>%s</td>", $table);
 			$exists = $tables[$table];
 			if (!$exists) {
	   		SQL_Query("CREATE TABLE $table ( $fields )");
 			}
   		printf("<td class=liste>%s</td>", ($exists) ? "Vorhanden" : "Angelegt");
   		echo "</tr>";
   		
   		return $exists;
   }
	
CreateTable("forum_posting", "
  id int(11) DEFAULT '0' NOT NULL auto_increment,
  date datetime DEFAULT '0000-00-00 00:00:00' NOT NULL,
  text text,
  ls_id int(11) DEFAULT '0',
  name varchar(100) DEFAULT '0',
  email varchar(200) DEFAULT '0',
  topic int(11) DEFAULT '0' NOT NULL,
  flags int(11) DEFAULT '0',
  PRIMARY KEY (id),
  KEY date_index (date)
");

CreateTable("forum_topic", "
  id int(11) DEFAULT '0' NOT NULL auto_increment,
  forum int(11) DEFAULT '0' NOT NULL,
  title varchar(255) DEFAULT '',
  pcount int(11) DEFAULT '0',
  PRIMARY KEY (id)
");

CreateTable("guest", "
  id int(11) unsigned DEFAULT '0' NOT NULL auto_increment,
  user int(11),
  flags int(11),
  PRIMARY KEY (id)
");

CreateTable("news", "
  id int(11) DEFAULT '0' NOT NULL auto_increment,
  author int(11) DEFAULT '0' NOT NULL,
  title varchar(255) DEFAULT '' NOT NULL,
  msg text,
  date datetime DEFAULT '0000-00-00 00:00:00' NOT NULL,
  options int(11) DEFAULT '0' NOT NULL,
  PRIMARY KEY (id)
");

CreateTable("orga", "
  id int(11) DEFAULT '0' NOT NULL auto_increment,
  user int(11) DEFAULT '0' NOT NULL,
  rights int(11) DEFAULT '0' NOT NULL,
  date datetime DEFAULT '0000-00-00 00:00:00' NOT NULL,
  PRIMARY KEY (id)
");

CreateTable("seat_block", "
  id int(11) DEFAULT '0' NOT NULL auto_increment,
  party int(11) DEFAULT '0',
  rows int(11) DEFAULT '0',
  cols int(11) DEFAULT '0',
  orientation int(11) DEFAULT '0',
  name varchar(255) DEFAULT '',
  text_tl varchar(255) DEFAULT '',
  text_tc varchar(255) DEFAULT '',
  text_tr varchar(255) DEFAULT '',
  text_lt varchar(255) DEFAULT '',
  text_lc varchar(255) DEFAULT '',
  text_lb varchar(255) DEFAULT '',
  text_rt varchar(255) DEFAULT '',
  text_rc varchar(255) DEFAULT '',
  text_rb varchar(255) DEFAULT '',
  text_bl varchar(255) DEFAULT '',
  text_bc varchar(255) DEFAULT '',
  text_br varchar(255) DEFAULT '',
  color varchar(100) DEFAULT '0',
  PRIMARY KEY (id)
");

CreateTable("seat_sep", "
  id int(11) DEFAULT '0' NOT NULL auto_increment,
  block int(11) DEFAULT '0',
  orientation int(11) DEFAULT '0',
  value int(11) DEFAULT '0',
  PRIMARY KEY (id)
");

CreateTable("seats", "
  id int(11) DEFAULT '0' NOT NULL auto_increment,
  block int(11) DEFAULT '0' NOT NULL,
  col int(11) DEFAULT '0' NOT NULL,
  row int(11) DEFAULT '0' NOT NULL,
  status int(11) DEFAULT '0' NOT NULL,
  guest int(11) DEFAULT '0',
  PRIMARY KEY (id)
");

CreateTable("tourney_matches", "
  id int(11) DEFAULT '0' NOT NULL auto_increment,
  tourney int(11),
  col int(11),
  row int(11),
  op1 int(11),
  op2 int(11),
  flags int(11) DEFAULT '0' NOT NULL,
  extratime int(11) DEFAULT '0' NOT NULL,
  score1 int(11) DEFAULT '0' NOT NULL,
  score2 int(11) DEFAULT '0' NOT NULL,
  grp int(11) DEFAULT '0' NOT NULL,
  PRIMARY KEY (id)
");

CreateTable("tourney_results", "
  id int(11) DEFAULT '0' NOT NULL auto_increment,
  tourney int(11) DEFAULT '0' NOT NULL,
  matchid int(11) DEFAULT '0' NOT NULL,
  round int(11) DEFAULT '0' NOT NULL,
  score1 float(10,2) DEFAULT '0.00' NOT NULL,
  score2 float(10,2) DEFAULT '0.00' NOT NULL,
  flags int(11) DEFAULT '0' NOT NULL,
  map varchar(255),
  PRIMARY KEY (id)
");

CreateTable("tourney_settings", "
  mtch int(11),
  team int(11),
  map varchar(255),
  teamtype varchar(255),
  flags int(11),
  tourney int(11) DEFAULT '0' NOT NULL
");

CreateTable("tourney_teammember", "
  team int(11),
  user int(11)
");

if (!CreateTable("tourney_teams", "
  id int(11) DEFAULT '0' NOT NULL auto_increment,
  tourney int(11),
  name varchar(255),
  leader int(11),
  def_map varchar(255),
  def_teamtype varchar(255),
  def_settings int(11),
  type int(11) DEFAULT '0' NOT NULL,
  position int(11) DEFAULT '0' NOT NULL,
  PRIMARY KEY (id)
")) {
SQL_Query("INSERT INTO tourney_teams VALUES (9,0,'Reserved',1,NULL,NULL,NULL,0,0)");
SQL_Query("INSERT INTO tourney_teams VALUES (7,0,'Reserved',1,NULL,NULL,NULL,0,0)");
SQL_Query("INSERT INTO tourney_teams VALUES (8,0,'Reserved',1,NULL,NULL,NULL,0,0)");
SQL_Query("INSERT INTO tourney_teams VALUES (6,0,'Reserved',1,NULL,NULL,NULL,0,0)");
SQL_Query("INSERT INTO tourney_teams VALUES (5,0,'Reserved',1,NULL,NULL,NULL,0,0)");
SQL_Query("INSERT INTO tourney_teams VALUES (4,0,'Reserved',1,NULL,NULL,NULL,0,0)");
SQL_Query("INSERT INTO tourney_teams VALUES (3,0,'Reserved',1,NULL,NULL,NULL,0,0)");
SQL_Query("INSERT INTO tourney_teams VALUES (2,0,'Freilos',1,NULL,NULL,NULL,0,0)");
SQL_Query("INSERT INTO tourney_teams VALUES (1,0,'Frei',1,NULL,NULL,NULL,0,0)");
};

CreateTable("tourneys", "
  id int(11) DEFAULT '0' NOT NULL auto_increment,
  name varchar(255),
  teamsize int(11),
  maxteams int(11),
  endtime datetime DEFAULT '0000-00-00 00:00:00' NOT NULL,
  maplist longblob,
  teamtypes longblob,
  scorename1 varchar(255),
  scorename2 varchar(255),
  grp int(11),
  flags int(11),
  rules varchar(255),
  settings longblob,
  icon varchar(255),
  rounds int(11) DEFAULT '0' NOT NULL,
  roundtime int(11) DEFAULT '0' NOT NULL,
  roundpause int(11) DEFAULT '0' NOT NULL,
  doubletimecols int(11) DEFAULT '0' NOT NULL,
  drawhandling int(11) DEFAULT '0' NOT NULL,
  options int(11) DEFAULT '0' NOT NULL,
  status int(11) DEFAULT '0' NOT NULL,
  delimit int(11) DEFAULT '0' NOT NULL,
  serverlist text NOT NULL,
  preround_groupsize int(11) DEFAULT '0' NOT NULL,
  preround_places int(4) DEFAULT '0' NOT NULL,
  maphandling int(4) DEFAULT '0' NOT NULL,
  PRIMARY KEY (id)
");

CreateTable("user", "
  id int(11) unsigned DEFAULT '0' NOT NULL auto_increment,
  clan varchar(255),
  name varchar(255),
  email varchar(255),
  pwd varchar(255) binary,
  realname1 varchar(255),
  realname2 varchar(255),
  homepage varchar(255),
  hometown varchar(255),
  birthyear int(11),
  flags int(11) DEFAULT '0',
  infotext varchar(255),
  forum_pagecount int(11) DEFAULT '0' NOT NULL,
  forum_signature text NOT NULL,
  ip_address VARCHAR (15),
  PRIMARY KEY (id)
");

?>
	</table>
</ul>
</p>
<p class=content>
<b>Intranet Daten Importieren:</b><br>

<?

	function split_sql($sql) {
		$ret = array();
		
		$in_comment = false;
		$in_string = false;
		$queryStart = 0;
		
		for ($i=0; $i < strlen($sql); $i++) {
			// begin of comment
			if (!$in_comment && !$in_string && $sql[$i] == '#') {
				$in_comment = true;
				continue;
			}
			// end of comment
			if ($in_comment && $sql[$i] == "\n") {
				$queryStart = $i;
				$in_comment = false;
			}
			// begin of string
			if (!$in_comment && !$in_string && $sql[$i] == "'") {
				$in_string = true;
				continue;
			}
			// during string
			if ($in_string) {
				if ($sql[$i] == "\\") {
					$i++;
					continue;
				} elseif ($sql[$i] == "'")
					$in_string = false;
			}
			
			// End of query
			if (!$in_comment && !$in_string && $sql[$i] == ';') {
				$ret[] = trim(substr($sql, $queryStart, $i - $queryStart));
				$queryStart = $i + 1;
			}
			
		}
		
		return $ret;
	}

	if (isset($action) && $action == "import") {
		echo 'Die Daten werden importiert bitte ein wenig gedult...<br>';
		flush();
		@set_time_limit(10000);
		
		
		if(!empty($sql_file) && $sql_file != "none")
		{
		    $sql_query = fread(fopen($sql_file, "r"), filesize($sql_file));
		}
		
		$pieces  = split_sql($sql_query);
		
		for ($i=0; $i<count($pieces); $i++)
	    {
			$q = $pieces[$i];
			if ($q)
	    	$result = SQL_Query($q);
	  }
	  echo "Die Daten wurden importiert.";
		
	}
?>
<form method="post" action="<? echo $PHP_SELF; ?>" enctype="multipart/form-data">
<input type="hidden" name="action" value="import">
.SQL Datei:<br>
<input type="file" name="sql_file"><br>
<input type="submit" name="SQL" value="Importieren">
</form>

<?
	die;
?>
--> <b>Nein</b> Web Server Konfiguration &Uuml;berpr&uuml;fen
