<?
	$LS_BASEPATH = "";
	include "../includes/lsi_base.inc";
	
	StartPage("", STYLE_NAVBAR);
	
	function PrintModule($title, $url, $enabled = TRUE) {
		global $LS_BASEPATH;
		
		echo "&nbsp;";
		NavPrintAction($url, $title);
		echo "<br>";
		
/*		printf('&nbsp;<img src="images/pixel.gif" width="16" height="8" border="0">
		<img src="images/diamond_grey.gif" width="15" height="15" border="0" align="top"> 
        <a href="%s">%s</a><br>', $url, $title);*/
	}
	
?>
<p>&nbsp;</p>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr> 
    <td colspan="2" valign="top"><img src="images/slice_02.gif" width="154" height="35"></td>
    <td valign="top" colspan="2">&nbsp;</td>
  </tr>  
	<tr> 
    <td width="128" valign="top"> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr bgcolor="#333333" valign="top"> 
          <td> 
            <p><img src="images/pixel.gif" width="5" height="1"><font face="Tahoma, Arial, sans-serif"> 
              </font></p>
          </td>
          <td>
          
<?
	if ($user_valid) {
		echo "<font size=2>Dein Status:</font><br>";
		printf('<font face="Tahoma, Arial, sans-serif"><b>%s</b></font><br><br>', $user_current['name']);
		NavPrintAction("party/details.phtml", "Details");
		
	} else {
		NavPrintAction("party/details.phtml", "Login");
  }
?>
					</td>
        </tr>
        <tr> 
          <td colspan="2"><img src="images/slice_13.gif" width="129" height="45"></td>
        </tr>
        <tr bgcolor="#333333" valign="top"> 
          <td colspan="2"> 
          
<?
	PrintModule("Neuigkeiten", "party/news.phtml");
	PrintModule("G&auml;steliste", "party/guests.phtml");
	PrintModule("Sitzplan", "party/seat.phtml");
	PrintModule("Turniere", "tourney/");
	PrintModule("Forum", "forum/index.phtml");
	
	if (user_auth_ex(AUTH_TEAM, 0, 0, FALSE)): ?>
	<p class=content>
	<?
		PrintModule("Admin Page", "orga/index.phtml");
	?>
	</p>
	<?
	 endif; 
	?>
            <div align="center"><br>
              <img src="images/lansurfer_button_surfer.gif" width="70" height="136"></div>
          </td>
        </tr>
      </table>
      
    </td>
    <td width="25" background="images/slice_06.gif" bgcolor="#99ccff">&nbsp;</td>
    <td valign="top" colspan="2">
    </td>
  </tr>
  <tr> 
    <td colspan="2" valign="top"><img src="images/slice_21.gif" width="154" height="47"></td>
    <td valign="top" colspan="2">&nbsp;</td>
  </tr>
</table>
