<?
	/*
	 * LANsurfer - Board Module
	 */
	
	$info['vendor'] = "LANsurfer";
	$info['vendorURL'] = "http://www.lansurfer.com";
	$info['displayname'] = _("Board");		// Name used for this module in Menu
	$info['version'] = LS_INTRANET_VERSION;
	$info['builddate'] = LS_INTRANET_BUILD_DATE;

	$info['menuitems'] = array(
		'board/' => _("Board"),
	);

	$info['orga_menuitems'] = array(
		'board/' => _("Board Configuration"),
	);

?>