<?
	define ("LS_CONFIGURED", FALSE);			// Nach anpassen dieser datei auf TRUE setzen
	define ("LS_IP_PUBLIC", FALSE);				// Auf True setzen falls die IP addressen der Addressvergabe 
																				// in der öffentlichen Gästeliste sichtbar sein sollen
	define ("LS_IP_WARN", FALSE);					// Benutzer warnen falls er nicht die korrekte IP Addresse 
																				// eingestellt hat

	define ("SQL_USER",     "root");			// der Benutzer von MySQL
	define ("SQL_PASSWORD", "");					// Passwort des Benutzers
	define ("SQL_DB", 	"db_intra"); 			// Datenbank in der die Tabellen gespeichert werden sollen
	define ("SQL_HOST",     "localhost");	// Addresse des MySQL Servers (im regelfall localhost)
?>
