<?
// Navigation 
	$NavStruct = array (
		array ("name" => "user", "title" => "Benutzer Status", "url" => "user.phtml"),
		array ("name" => "orga", "title" => "Orga Team", "url" => "orga/?id=%team%"),
		array ("name" => "party", "title" => "Party Kontrolle", "url" => "orga/party/?id=%party%"),
		array ("name" => "guestlist", "title" => "G&auml;steliste", "url" => "orga/guests.phtml"),
		array ("name" => "tourney", "title" => "Turniere", "url" => "tourney/"),
		array ("name" => "singletourney", "title" => "Turnier", "url" => "tourney/show.phtml?id=%tid%")
	);


?>
