<?
// Navigation 
	$NavStruct = array (
		array ("name" => "user", "title" => _("My Status"), "url" => "party/details.php"),
		array ("name" => "orga", "title" => _("Orga Team"), "url" => "orga/"),
		array ("name" => "party", "title" => _("Party Control"), "url" => "orga/party/"),
		array ("name" => "guestlist", "title" => _("Guest list"), "url" => "orga/guests.php"),
		array ("name" => "guestdetail", "title" => _("Guest Details"), "url" => "orga/guest_detail.php?id=%guestid%"),
		array ("name" => "tourney", "title" => _("Tournaments"), "url" => "_tourney/"),
		array ("name" => "singletourney", "title" => _("Tourney"), "url" => "tourney/teams.php?id=%tid%"),
		array ('name' => 'tournaments', 'title' => _("Tournaments"), 'url' => 'tourney/'),
		array ('name' => 'teams', 'title' => _("Partcipants"), 'url' => 'tourney/teams.php?id=%tid%')
	);


?>
