<?
	$LS_BASEPATH = "../";
	include $LS_BASEPATH."../includes/ls_base.inc";

	if ($action == "login") {
		$login_error = user_login($form_id, $form_password);
	} elseif ($action == "logout") {
		user_logout();
	}

	StartPage("Meine Details", $party);

	if ($action == "logout" || $action == "login") {
?>
  <script language="JavaScript">
  <!--
  var status_frame = parent.frames["navbar"];
  if (status_frame.location) {
  	var url = status_frame.location.href;
  	status_frame.location.replace(url);
  }
  //-->
  </script>
<?
	}

	user_auth();

	if (!($user_valid) || $login_error || $action == "logout") {
		?>
		<p class=content>
		Du musst f&uuml;r diese Party angemeldet sein um dich einloggen zu k&ouml;nnen.
		</p>
		<?

		FormStart("action=\"".$PHP_SELF."\" method=\"post\"");
			if ($login_error == 1)
				FormError("form_id", "Unbekannte Email bzw. UserID");
			elseif ($login_error == 2)
				FormError("form_password", "Das Passwort ist nicht richtig");

			FormGroup("Login");
			FormValue("action", "login");
			FormValue("party", $party);
			FormElement("form_id", "Email oder LanSurfer-ID", $form_id);
			FormElement("form_password", "Passwort", "", "password");
			FormElement("", "", "Login", "submit");
		FormEnd();

	} else {

		$res = SQL_Query("SELECT * FROM guest WHERE user=".$user_current[id]);
		$Guest = mysql_fetch_array($res);

		if ($Guest) {
			$res = SQL_Query("SELECT * FROM seats WHERE guest=".$Guest[id]." AND status=".SEAT_OCCUPIED);
			$Seat = mysql_fetch_array($res);
		}

?>
	<h3 class="content">Meine Daten:</h3>
	<p class="content">
	<table class="content">
	<? NavPrintAction("details_edit.phtml?party=$party", "Daten &auml;ndern") ?><br>
	<br>
	<?
		function PrintValue($caption, $name, $addition) {
			global $user_current;

			echo "<tr class=\"contentpanel\"><td align=\"right\" class=\"contentpanel\"><b>$caption</b>:</td><td class=\"contentpanel\">";
			if ($name == "email")
				echo "<a href=\"mailtto:".$user_current[$name]."\">".HTMLStr($user_current[$name])."</a>";
			else
				echo HTMLStr($user_current[$name]);
			echo $addition."</td></tr>\n";
		}
		PrintValue("Name", "name", "");
		PrintValue("Clan", "clan", "");
		PrintValue("Vorname", "realname1", "");
		PrintValue("Email", "email", "");
		if (LS_IP_WARN) {
			if ($user_current["ip_address"] == "")
			  $addition = "<font color='red'>Dir wurde keine IP-Adresse zugewiesen - bitte melde dich bei einem Orga!</font>";
	   	PrintValue("Zugewiesene<br>IP-Adresse", "ip_address", $addition);
	?>
	<tr class="contentpanel"><td align="right" class="contentpanel"><b>Derzeitige<br>IP-Adresse</b>:</td><td class="contentpanel">
  <?
    if (getenv(HTTP_X_FORWARDED_FOR))
    {
      $ip=getenv(HTTP_X_FORWARDED_FOR);
    }
    else
    {
      $ip=getenv(REMOTE_ADDR);
    }
    echo $ip;
    if ($user_current["ip_address"] == $ip)
      echo " -> alles klar";
    else
      if ($user_current["ip_address"] != "")
        echo " -> <font color='red'>Fehlkonfiguration! Bitte ändere Deine IP-Adresse auf ".$user_current["ip_address"]."!</font>";
  ?>
</td></tR>
<?
	  }
?>

	</table>
	</p>

  <font color="red">Bitte beachten:</font> Ihr müßt Cookies aktiviert haben um korrekt eingeloggt zu sein!<p>

	<p>&nbsp;</p>
	<p class="content">
	<? NavPrintAction($PHP_SELF."?action=logout&party=$party", "Logout"); ?><br>
	</p>

<?

	}

	EndPage();

?>
