<?
	$LS_BASEPATH = "../";
	include $LS_BASEPATH."../includes/ls_base.inc";

	$res = SQL_Query("SELECT * FROM seat_block WHERE id=$block");
	$Block = mysql_fetch_array($res);
	
	NavAdd("Sitzplan", "seat.phtml?id=".$Block[id]);
	
	StartPage("Sitzplatz Reservierung");

	if ($row > $Block[rows] || $col > $Block[cols] || $col < 0 || $row < 0)
		LS_Error("Ung&uuml;ltige Parameter");
		
	// =================== Eigenen Status Ermittlen ===========================

	$res = SQL_Query("SELECT * FROM guest WHERE user=".$user_current[id]." AND (flags & ".GUEST_PAID.")");
	$Guest = mysql_fetch_array($res);
	if (!$Guest)
		LS_Error("Du must bei dieser Party angemeldet sein und bezahlt haben, um einen Sitzplatz zu reservieren.", TRUE, TRUE);

	$res = SQL_Query("SELECT * FROM seats WHERE guest=".$Guest[id]." AND (status=".SEAT_OCCUPIED.")");
	$Seat_Own = mysql_fetch_array($res);
	$res = SQL_Query("SELECT COUNT(*) FROM seats WHERE guest=".$Guest[id]." AND status=".SEAT_RESERVED);
	$ReserveCount = mysql_result($res, 0, 0);
	
	// Status Des Platzes
	$res = SQL_Query("SELECT * FROM seats WHERE block=".$Block[id]." AND col=$col AND row=$row");
	$Seat = mysql_fetch_array($res);
	
	if ($Seat)
		$seat_status = $Seat[status];
	else
		$seat_status = 0;

/*	echo "DEBUG: <br>ResCount: $ReserveCount OwnSeat: ".$Seat_Own[col].", ".$Seat_Own[row]."<br>";
	echo "Seat Status: $seat_status";
	echo "/DEBUG<br>"; */
	
	if ($seat_status == SEAT_DELETED)
		LS_Error("Dieser Platz kann nicht Reserviert werden.");
		
	$seatname = $Block[name].", Reihe ".chr($row + 65).", Platz ".($col + 1);

	if ($submited) {
		if ($action == "use") {
			if ($Seat[status] == SEAT_OCCUPIED)
				LS_Error("Der Sitzplatz ist bereits belegt.");
		
			if (!$Seat_Own) {
				$new_status = SEAT_OCCUPIED;
				$text = "Der Platz $seatname wurde f&uuml;r dich Reserviert.";
			} else {
				$new_status = SEAT_RESERVED;
				$text = "Der Platz $seatname wurde f&uuml;r dich vorgemerkt. Diese Angabe ist f&uuml;r niemanden verbindlich und ist lediglich zur Orientierung gedacht.";
			}
			$fields = "guest=".$Guest[id].",status=".$new_status;
			if ($Seat)
				SQL_Query("UPDATE seats SET $fields WHERE id=".$Seat[id]);
			else
				SQL_Query("INSERT INTO seats SET $fields,col=$col,row=$row,block=$block");
			echo $text."<br>";
		} elseif ($action == "free") {
			SQL_Query("DELETE FROM seats WHERE col=$col AND row=$row AND block=$block");
			echo "Der Sitzplatz wurde freigegeben.";
		}
	
	} else {
		if ($Seat[guest] == $Guest[id]) {
			$action = "free";
			$btn_caption = "Freigeben";
			if ($Seat[status] == SEAT_OCCUPIED)
				echo "Der Sitzplatz $seatname ist f&uuml;r dich zur Zeit <i>reserviert</i>.<br>
					Wenn Du willst kannst du ihn wieder freigeben und einen anderen Sitzplatz f&uuml;r Dich reservieren.";
			elseif ($Seat[status] == SEAT_RESERVED)
				echo "Der Sitzplatz $seatname ist f&uuml;r dich zur Zeit <i>vorgemerkt</i>.<br>
					Wenn Du willst kannst Du ihn wieder freigeben.";
		} elseif ($seat_status == SEAT_OCCUPIED) {
			LS_Error("Dieser Platz ist bereits belegt");
		} elseif ($seat_status == SEAT_RESERVED || $seat_status == 0) {
			$action = "use";
			if ($seat_status == 0)
				echo "Der Sitzplatz $seatname ist noch <i>frei</i>.<br>";
			elseif ($seat_status == SEAT_RESERVED)
				echo "Der Sitzplatz $seatname ist von einem anderen Gast schon <i>vorgemerkt</i>.<br>";
			if ($Seat_Own) {
				if ($ReserveCount >= 4)
					LS_Error("Du kannst nur bis zu <b>4</b> Sitzpl&auml;tze vormerken.");
				$btn_caption = "Vormerken";
				echo "Du kannst ihn nun Vormerken.";
			} else {
				$btn_caption = "Reservieren";
				echo "Du kannst ihn nun f&uuml;r Dich reservieren.";
			}
		}

		FormStart();
			FormValue("action", $action);
			FormValue("block", $block);
			FormValue("row", $row);
			FormValue("col", $col);
			FormValue("submited", 1);
			FormElement("", "", $btn_caption, "submit");
		FormEnd();
	}

	NavPrintBack();
	
	EndPage();
?>