<?
  $LS_BASEPATH = "../";
  require $LS_BASEPATH."../includes/lsi_base.inc";
  include $LS_BASEPATH."../includes/tourney.inc";


	StartPage("Fix");
	
	if (!isset($id))
		LS_Error("No ID");
	
	$res = SQL_Query("SELECT tt.leader AS 'teamleader', tt.id AS 'teamid', u.id AS 'uid', u.name AS 'username', u.clan AS 'userclan'FROM tourney_teams AS tt LEFT JOIN tourney_teammember AS tm ON tt.id=tm.team LEFT JOIN user AS u ON tm.user=u.id WHERE tt.tourney=$id");
	while ($row=mysql_fetch_array($res)) {
		if ($row[teamleader] != $row[uid]) {
			echo $row[teamid]." ".$row[uid]."<br>";
			SQL_Query("INSERT INTO tourney_teams SET tourney=$id, leader=".$row[uid]."");
			$newteam = mysql_insert_id();
			SQL_Query("UPDATE tourney_teammember SET team=$newteam WHERE user=".$row[uid]." AND team=".$row[teamid]);

			echo "<br>";
			
			echo "Fixed...";
		}
	}
	
	EndPage();

?>