<?
  $LS_BASEPATH = "../";
  require $LS_BASEPATH."../includes/lsi_base.inc";
  include $LS_BASEPATH."../includes/tourney.inc";
  
  NavStruct("tourney/");

	if (!isset($action)) {
		if (isset($id))
			$action = "edit";
		else
			$action = "new";
	}

	switch ($action) {
		case "new":
			$PageTitle = "Neues Turnier Anlegen";
		default:
			$PageTitle = "Turnier Bearbeiten";
	}

	StartPage($PageTitle);

  user_auth_ex(AUTH_TOURNEY, -1);

	function deStrToDate($date, $time = "") {
		$thedate = -1;
		
		list( $day, $month, $year ) = split( '[/.-]', $date );
		
		if ($time)
			list($hour, $minute) = split( '[:.-]', $time );
		
		if (checkdate($month, $day, $year))
			$thedate = mktime($hour, $minute, 0, $month, $day, $year);
		else
			$thedate = -1;
		
		return $thedate;
	}

	
	if ($action == "edit" || $action == "new") {
		if ($submitted) {
			if ($f_name == "")
				FormErrorEx("f_name", "Kein Name angegeben");
			if ($f_teamsize < 1)
				FormErrorEx("f_teamsize", "Keine Teamgroesse angegeben");
			if ($f_maxteams < 8)
				FormErrorEx("f_maxteams", "Mindestens 8 Team ben&ouml;ntigt");
			if ($f_group < 1)
				FormErrorEx("f_group", "Keine gruppe angegeben");
				
			$f_end = deStrToDate($f_end_date, $f_end_time);
			
			if ($f_end < 0)
				FormErrorEx("f_end_time", "Keine G&uuml;ltige Endzeit");
			elseif ($f_end < time())
				FormErrorEx("f_end_time", "Endzeit darf nicht vor jetzt liegen");
				
			if ($f_roundlength <= 0)
				FormErrorEx("f_roundlength", "Kein Rundenlänge angegeben");
			if ($f_roundpause == "")
				FormErrorEx("f_roundpause", "Kein Rundenpause angegeben");
			if ($f_doubletimecount == "")
				FormErrorEx("f_doubletimecount", "Kein Rundenpause angegeben");
			
			if (!$FormErrorCount) {
				$newflags = $oldflags;
				
				if ($f_timelock)
					$newflags |= $TF_TIMECHECK;
				else
					$newflags &= ~$TF_TIMECHECK;

				if ($f_fixedmaps)
					$newflags |= $TF_DEFMAPS;
				else
					$newflags &= ~$TF_DEFMAPS;
				
				if ($f_groupignore)
					$newflags |= $TF_NOJOINCHECK;
				else
					$newflags &= ~$TF_NOJOINCHECK;
				
				
				$fields = SQL_QueryFields(array(
					"name" => $f_name,
					"teamsize" => $f_teamsize,
					"maxteams" => $f_maxteams,
					"grp"	=> $f_group,
					"rules" => $f_rulefile,
					"icon" => $f_icon,
					
					"roundtime" => $f_roundlength,
					"rounds" => $f_roundcount,
					"roundpause" => $f_roundpause,
					"doubletimecols" => $f_doubletimecount,
					"scorename1" => $f_scorename1,
					"scorename2" => $f_scorename2,
					"teamtypes" => $f_teamtypes,
					"maplist" => $f_maplist,
					"settings" => $f_settings,
					"flags" => $newflags,
					"drawhandling" => $f_drawhandling
					)).
					", endtime=FROM_UNIXTIME($f_end)";
				
//				echo nl2br($fields);
				
				if ($action == "new")
					SQL_Query("INSERT INTO tourneys SET $fields");
				else
					SQL_Query("UPDATE tourneys SET $fields WHERE id=$id");
				
				echo "<p class=content>Das Turnier wurde angelegt/gespeichert.</p>";
			}
			
		} else {
			if ($action == "new") {
				$f_teamsize = 1;
				$f_maxteams = 32;
				$f_group = 1;
				$f_roundlength = 10;
				$f_roundpause = 10;
				$f_roundcount = 2;
				$f_doubletimecount = 0;
				$f_timelock = 1;
				$oldflags = $MF_TIMECHECK;
				
				$f_end = time() + (60 * 60) * 12;
			} else {
				$res = SQL_Query("SELECT *, UNIX_TIMESTAMP(endtime) as endT FROM tourneys WHERE id=$id");
				$Tourney = mysql_fetch_array($res);
				
				$oldflags = $Tourney[flags];
				$f_name = $Tourney[name];
				$f_teamsize = $Tourney[teamsize];
				$f_maxteams = $Tourney[maxteams];
				$f_group = $Tourney[grp];
				$f_rulefile = $Tourney[rules];
				$f_icon = $Tourney[icon];
				
				$f_end = $Tourney[endT];
				$f_roundlength = $Tourney[roundtime];
				$f_roundcount = $Tourney[rounds];
				$f_roundpause = $Tourney[roundpause];
				$f_doubletimecount = $Tourney[doubletimecols];
				$f_scorename1 = $Tourney[scorename1];
				$f_scorename2 = $Tourney[scorename2];
				$f_maplist = $Tourney[maplist];
				$f_teamtypes = $Tourney[teamtypes];
				$f_settings = $Tourney[settings];
				$f_drawhandling = $Tourney[drawhandling];
			}
			$f_end_date = date("d.m.Y", $f_end);
			$f_end_time = date("H:i", $f_end);
		}
		
		if (!$submitted || $FormErrorCount) {
			FormStart();
				FormValue("submitted", 1);
				FormValue("action", $action);
				FormValue("id", $id);
				FormValue("oldflags", $oldflags);
				
				FormGroup("Allgemeine Angaben");			
				FormElement("f_name", "Name des Turniers", $f_name, "text", "size=30");
				FormElement("f_teamsize", "Spieler pro Team", $f_teamsize, "text", "size=2 maxlength=4");
				FormElement("f_maxteams", "Maximale Teams", $f_maxteams, "text", "size=2 maxlength=4");
				FormElement("f_group", "Gruppe", $f_group, "text", "size=2 maxlength=4");

				FormSelectStart("f_rulefile", "Datei mit Regeln", $f_rulefile);
					FormSelectItem("(Keine Regeln)", "");
					$dir = opendir("rules/");
					while (($file = readdir($dir))!=false) {
						if ($file != "." && $file != "..")
    					FormSelectItem($file, $file);
					}
					closedir($dir); 
				FormSelectEnd();

//				FormElement("f_rulefile", "Datei mit Regeln", $f_rulefile, "text", "size=30");
//				FormElement("f_icon", "Icon", $f_icon, "text", "size=30");
				
				FormSelectStart("f_icon", "Icon", $f_icon);
					FormSelectItem("(Icon Datei Ausw&auml;hlen)", "");
					$dir = opendir("../images/tourney/icons/");
					while (($file = readdir($dir))!=false) {
						if ($file != "." && $file != "..")
    					FormSelectItem($file, $file);
					}
					closedir($dir); 
				FormSelectEnd();
				
				FormElement("f_groupignore", "Gruppe Ignorieren", 1, "checkbox", ($oldflags & $TF_NOJOINCHECK) ? "checked" : "");
	
				FormGroup("Zeit Angaben (Alle Zeitangaben in Minuten)");
				FormElement("f_end_date", "Turnier Ende", $f_end_date, "text", "size=10 maxlength=10", 1);
					FormElement("f_end_time", "", $f_end_time, "text", "size=5 maxlength=5", -1);
				FormElement("f_roundlength", "Rundenl&auml;nge", $f_roundlength, "text", "size=2 maxlength=4");
				FormElement("f_roundcount", "Rundenanzahl", $f_roundcount, "text", "size=2 maxlength=4");
				FormElement("f_roundpause", "Pause pro Runde", $f_roundpause, "text", "size=2 maxlength=4");
				FormElement("f_doubletimecount", "Runden mit Doppelter Zeit", $f_doubletimecount, "text", "size=2 maxlength=4");
				FormElement("f_timelock", "Strenge Zeiten", 1, "checkbox", ($oldflags & $TF_TIMECHECK) ? "checked" : "");
	
				FormGroup("Ergebnisse und Einstellungen");
				FormElement("f_scorename1", "Ergebnisname 1", $f_scorename1, "text", "size=10");
				FormElement("f_scorename2", "Ergebnisname 2", $f_scorename2, "text", "size=10");
				FormSelectStart("f_drawhandling", "Unentschieden", $f_drawhandling);
					FormSelectItem("Eine einzelne Runde mit Voller Zeit", DRAW_SINGLE);
					FormSelectItem("Einzelne Runde mit Halber Zeit", DRAW_SINGLE_HALF_TIME);
					FormSelectItem("2 Runden mit Halber Zeit", DRAW_DOUBLE_HALF_TIME);
				FormSelectEnd();
				
				FormElement("f_maplist", "Map Liste", $f_maplist, "textarea", "rows=10 cols=20");
				FormElement("f_fixedmaps", "Feste Maps", 1, "checkbox", ($oldflags & $TF_DEFMAPS) ? "checked" : "");
				FormElement("f_teamtypes", "Team Typen", $f_teamtypes, "textarea", "rows=3 cols=20");
				FormElement("f_settings", "Settings", $f_settings, "textarea", "rows=5 cols=20");
			
				FormElement("", "", ($action == "new") ? "Anlegen" : "Speichern", "submit");
			FormEnd();
		}
	} elseif ($action == "delete") {
		
		if ($submitted) {
			SQL_Query("DELETE FROM tourneys WHERE id=$id");
			printf("<p class=conten>Das Turnier wurde entfernt.</p>");
			
		}
		
		if (!$submitted) {
			$res = SQL_Query("SELECT name FROM tourneys WHERE id=$id");
			$Tourney = mysql_fetch_array($res);

			printf("<p class=conten>Bist du sicher das du das Turnier <i>%s</i> <b>entfernen</b> willst?</p>", HTMLStr($Tourney[name]));
			FormStart();
				FormValue("action", $action);
				FormValue("id", $id);
				FormValue("submitted", 1);
				
				FormElement("", "", "Entfernen", "submit");
			FormEnd();
		}
	}
	
	NavPrintBack();
	
	EndPage();

?>