<?
   $CSS_PATH = "../";
   $LMS_PATH = "../";
   
   require $LMS_PATH."scripts/user.inc";
   user_authorize();

	function utime()
	{
	    $time = explode(" ", microtime());
	    $usec = (double)$time[0];
	    $sec = (double)$time[1];
	    return $sec + $usec;
	}
  
  SQL_Init();

  include "tourney.inc";

?>
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Turniere</title>
<? require "../scripts/style.inc"; ?>
</head>

<body bgcolor="#000000" text="#77DC6E" link="#00CC00" vlink="#1A5614" alink="#77DC6E">

<? if ($action == "show"): ?>

<?
	$tourney = new Tourney;		// Create Dummy tourney

	// Turnier Object initialisiere	
	$tourney->teamcount = $playercount;
	$tourney->matchcount = $matchcount;
	$tourney->matchlength = $matchtime;
	$tourney->matchpause = $roundpause;
	$tourney->doubletimecols = $extratimerounds;
		
	$colcount = 0;
	$matches = 1;
	while ($matches * 2 < $playercount ) {
	  $matches*=2;
	  $colcount++;
	}
	$maxmatches = $matches;

  if ($result=mysql_query("SELECT UNIX_TIMESTAMP('$theend') as 'endtime'")) {
  	if ($row=mysql_fetch_array($result))
  		$tourney->endtime = $row[endtime];
  }
  else
  	echo mysql_error()."<br>";

	$tourney->InitTiming(true);
?>

<div align=center>
<table border=0 cellspacing=0 CELLPADDING=0 width=<? echo ((8 + 100 + 8) *(($colcount * 3) + 2)); ?> height=<? echo ($maxmatches + 2) * 48; ?>>
  <colgroup width=116 span=<? echo ($colcount * 3) + 2 ?>>
  </colgroup>
  <tr>
  <?
    $currentcol = -($colcount * 2);
    while ($currentcol <= $colcount + 1) {
    	$round = $tourney->GetNextRound();
    	
    	echo "<td align=center><font face=\"Verdana\" size=1>";
    	echo "<b>Runde $round->dispindex</b><br><font color=#A0A0A0>bis $round->endtimeStr</font></td>\n";

    	$currentcol++;
    }
  ?>
  </tr>
  <tr>
  <?
    $TDM_HEIGHT = 48;
    $TDM_SPANWIDTH = 8;
    $TDM_WIDTH = 100;
  
    $currentcol = -($colcount * 2);
    $divisor = $matches;
    $extracol = TRUE;

		$starttime=utime();


    while ($currentcol <= $colcount + 1) {
      $colplayercount =  (($maxmatches * 2) / ($divisor));
      $matchcount = ($colplayercount / 2);

    	if ($currentcol < -1 && $matchcount > 1)
    		$looserSrcRow = $matchcount / 2;
    	else
    		$looserSrcRow = $matchcount;
    
      echo "<td width=116 height=".(($maxmatches + 2) * 48).">";
/*      echo "<div align=center><b>$currentcol</b></div>";
      echo "<br>Matches: $matchcount"; */
      echo "<table border=0 cellspacing=0 CELLPADDING=0 width=116>";
      $i = 0;
        if ($currentcol < -1 || $currentcol == $colcount + 1) {
        	if ($currentcol == $colcount + 1)
        		$j = ($currentcol - 1);
        	else
        		$j = 0;
        	while ($j < abs($currentcol)) {
        		echo "<tr>
        			<td width=$TDM_SPANWIDTH height=$TDM_HEIGHT><img width=8 height=48 src=\"".LMS_GRAPH_PATH."tourney/blank.gif\"></td>
        			<td width=$TDM_WIDTH height=$TDM_HEIGHT><font face=Verdana size=1><br><br><br></font></td>
        			<td width=$TDM_SPANWIDTH height=$TDM_HEIGHT><img width=8 height=48 src=\"".LMS_GRAPH_PATH."tourney/blank.gif\"></td>
        		</tr>\n";
        		$j++;
        	}
        }
      while ($i < $matchcount) {
      	echo "<tr>";
      	
     		// Linke Seite des Matches
     		echo "<td width=$TDM_SPANWIDTH height=$TDM_HEIGHT><img width=8 height=48 src=\"".LMS_GRAPH_PATH."tourney/";
     		if ($currentcol <= 0) {
     		  if (!($i % 2)  || (!$extracol && $currentcol < 0))
     		  	echo "top_right";
     		  else
     		    echo "bottom_right";
     		} else 
     			echo "middle";
  		  echo ".gif\"></td>";
      	
      	// Match Selber
      	echo "<td width=$TDM_WIDTH height=$TDM_HEIGHT bgcolor=";
      	if ($extracol || ($currentcol == 0 && ($i % 2)))
      		echo "#151515";
      	else
      		echo "#202020";
      	echo " align=center width=100><font face=Verdana size=1>";
      	if ($currentcol == -1)
      		echo "<font color=#A0A0A0>Verlierer ".(($i * 2) + 1)."</font>";
      	elseif ($currentcol == 1)
      		echo "<font color=#A0A0A0>Gewinner ".(($i * 2) + 1)."</font>";
      	elseif ($currentcol > 1 && $currentcol <= $colcount)
      		echo "<font color=#A0A0A0>Gewinner ".chr($currentcol + 63).(($i * 2) + 1)."</font>";
      	elseif ($currentcol == 0)
      		echo "<font color=#77DC6E>Spieler ".(($i * 2) + 1)."</font>";
      	else
      		echo "<font color=#A0A0A0>???</font>";
      	echo "<br><font size=1 color=white>vs</font><br>";
      	if ($currentcol == -1)
      		echo "<font color=#A0A0A0>Verlierer ".(($i * 2) + 2)."</font>";
      	elseif ($currentcol == 1)
      		echo "<font color=#A0A0A0>Gewinner ".(($i * 2) + 2)."</font>";
      	elseif ($currentcol > 1 && $currentcol <= $colcount)
      		echo "<font color=#A0A0A0>Gewinner ".chr($currentcol + 63).(($i * 2) + 2)."</font>";
      	elseif ($currentcol == 0)
      		echo "<font color=#77DC6E>Spieler ".(($i * 2) + 2)."</font>";
      	else
      		echo "<font color=#A0A0A0>???</font>";
      	echo "</font></td>";

				// Rechte Seite des Matches
     		echo "<td width=$TDM_SPANWIDTH height=$TDM_HEIGHT><img width=8 height=48 src=\"".LMS_GRAPH_PATH."tourney/";
     		if ($currentcol >= 0) {
     		  if ($i % 2)
     		  	echo "bottom_left";
     		  else
     		    echo "top_left";
     		} else 
     			echo "middle";
  		  echo ".gif\"></td>";

      	echo "</tr>";
      	$i++;
        if ($i > 0) {
          $dest = $divisor;
          if ($i >= $matchcount)
          	$dest = 2;
          $j = 1;
          while ($j < abs($dest)) {
        		echo "<tr>";
       		  echo "<td width=$TDM_SPANWIDTH height=$TDM_HEIGHT><img width=8 height=48 src=\"".LMS_GRAPH_PATH."tourney/";
       		  $text = "<br><br><br>";
        		if ($currentcol < 0 && ($i % 2 || !$extracol) ) {
        			if (!$extracol) {
        				if ($j == 1) {
        		  		echo "bottom_right";
//        		  		$text = "<br>&nbsp;&nbsp;Verlierer ".chr(abs($currentcol / 2) + 65).($matchcount - $i + 1)."<br><br>";
        		  		$text = "<br>&nbsp;&nbsp;Verlierer ".chr(abs($currentcol / 2) + 65).($looserSrcRow)."<br><br>";
        		  		$looserSrcRow--;
        		  		if ($looserSrcRow == 0)
        		  			$looserSrcRow = $matchcount;
        		  	}
        		  	else
        		  		echo "blank";
        		  }
        		  else {
        		  	if ($currentcol == -($colcount * 2)) {
        		  		echo "bottom_right";
        		  		$text = "<br>&nbsp;&nbsp;Zum Finale<br><br>";
        		  	}
        		  	else
        		  		echo "right";
        		  }
        		}
        		else 
        		  echo "blank";
        		if ($currentcol > 0 && $j == 1) {
        			$text = "<div align=right>".chr($currentcol + 64).$i."<br><br><br></div>";
        			if ($currentcol == $colcount)
        		  		$text = "<div align=right><br>Gewinner der&nbsp;&nbsp;<br>Loosers Bracket<br></div>";
        			if ($currentcol > $colcount)
        		  		$text = "<div align=right><br>Gewinner des Turniers&nbsp;&nbsp;<br><br></div>";
        		}
       		  echo ".gif\"></td>";
        		echo "<td><font face=\"Verdana\" size=1 color=#A0A0A0>$text</font></td>";
        		echo "<td><img width=8 height=48 src=\"".LMS_GRAPH_PATH."tourney/";
        		if ($currentcol >= 0 && ($i % 2)) {
        			if ($currentcol >= $colcount)
        				echo "bottom_left";
        			else
        		  	echo "left";
        		}
        		else
        		  echo "blank";
        		echo ".gif\"></td>";
        		echo "</tr>";
        		$j++;
        	}
        }
      }
      
      echo "</table>";
      
      echo "</td>";
      if (!$extracol) {
	      if ($currentcol < 0)
	      	$divisor /= 2;
	      else
	      	$divisor *= 2;
	    }
      $currentcol++;
      if ($currentcol < 0)
     		$extracol = !$extracol;
     	else
     		$extracol = FALSE;
    }

  
  ?>
  </tr>
</table>
</div>

<?
printf("\rDone, took %.2f seconds.\n", ($idle_while=utime()-$starttime));
?>

<? else: ?>
<p class=topic>tplan</p>

<p>
<font face=Verdana size=2>
</font>
	<form action="<? echo $PHP_SELF; ?>" method="post">
		<table>
		  <tr>
		  	<td width=250><font face=Verdana size=2>Spieler:</font></td>
		  	<td><input type="edit" class="editfield" name="playercount" value="16" size=3></td>
		  </tr>
		  <tr>
		  	<td width=250><font face=Verdana size=2>Minuten pro Spiel</font></td>
		  	<td><input type="edit" class="editfield" name="matchtime" value="10" size=3></td>
		  </tr>
		  <tr>
		  	<td width=250><font face=Verdana size=2>Spiele pro Runde</font></td>
		  	<td><input type="edit" class="editfield" name="matchcount" value="2" size=3></td>
		  </tr>
		  <tr>
		  	<td width=250><font face=Verdana size=2>Pause pro Runde (Minuten)</font></td>
		  	<td><input type="edit" class="editfield" name="roundpause" value="10" size=3></td>
		  </tr>
		  <tr>
		  	<td width=250><font face=Verdana size=2>Runden mit Doppelter Zeit</font></td>
		  	<td><input type="edit" class="editfield" name="extratimerounds" value="2" size=3></td>
		  </tr>

		  <tr>
		  	<td width=250><font face=Verdana size=2>Endzeit</font></td>
		  	<td><input type="edit" class="editfield" name="theend" value="2000-04-01 00:00" size=20></td>
		  </tr>
		  
		</table>
		<br><br>
		<input type="hidden" name="action" value="show">
		<input type="submit" class="btn" value=" Anzeigen ">
		<input type="reset" class="btn" value=" Reset ">
	</form>
</p>

<? endif; ?>



<? tourney_footer(); ?>

</body>

</html>
