<?
  $LS_BASEPATH = "../";
  require $LS_BASEPATH."../includes/lsi_base.inc";
  include $LS_BASEPATH."../includes/tourney.inc";
  

	$tourney = new Tourney($tid);
	if ($tourney->info[maplist])
		$maplist = split("\n", $tourney->info[maplist]);
	if ($tourney->info[teamtypes])
		$teamtypes = split("\n", $tourney->info[teamtypes]);
	if ($tourney->info[settings])
		$settings = split("\n", $tourney->info[settings]);


	NavAdd("Turniere", $LS_BASEPATH."tourney/");
	NavAdd($tourney->info[name], "show.phtml?id=$tid");

	function CheckTourneyGroup() {
		global $tourney, $user_current;
		
	 	// Gruppe Checken
	 	if (!($tourney->info[flags] & TF_NOJOINCHECK)) {
	 		$res = SQL_Query("SELECT t.name
	 			FROM tourneys AS t
	 				LEFT JOIN tourney_teams AS tt ON tt.tourney=t.id
	 				LEFT JOIN tourney_teammember AS tm ON tm.team=tt.id
	 			WHERE user=".$user_current[id]." AND t.grp=".$tourney->info[grp]."");
	 		if ($row = mysql_fetch_array($res)) {
	 			LS_Error(sprintf("Du bist bereits beim %s Turnier in dieser Gruppe Angemeldet.", $row[name]));
	 		}
	 	}
	}


  StartPage("Teilnehmen");
  
  if (!$user_valid)
  	LS_Error("Du musst eingelogged sein.");
  
	// ========================================================================================
	// Team Gründen
	// ========================================================================================
	if ($action == "signup"):
		CheckTourneyGroup();
		$res = SQL_Query("SELECT COUNT(*) FROM tourney_teams WHERE tourney=$tid");
		$TeamCount = mysql_result($res, 0, 0);
		if ($TeamCount >= $tourney->info[maxteams])
			LS_Error(sprintf("Es sind bereits %d Teilnehmer angemeldet.", $TeamCount));
		
		if ($submitted) {
			if (!$f_teamname && $tourney->info[teamsize] > 1)
				FormErrorEx("f_teamname", "Es muss ein Teamname angegeben werden.");
			if (!$f_rules)
				FormErrorEx("f_rules", "Du musst die Regeln akzeptieren.");
				
			if (!$FormErrorCount) {
				$s = 1;
				$setting = 0;
				for ($i = 0; $i < count($settings); $i++) {
					if ($f_setting[$i])
						$setting |= $s;
					$s *=2;
				}
				
				SQL_Query("INSERT INTO tourney_teams SET ".SQL_QueryFields(array(
					"tourney" => $tid,
					"name" => $f_teamname,
					"leader" => $user_current[id],
					"def_map" => $maplist[$f_map],
					"def_teamtype" => $teamtypes[$f_teamtype],
					"def_settings" => $setting
				)));
				SQL_Query("INSERT INTO tourney_teammember SET ".SQL_QueryFields(array(
					"user" => $user_current[id],
					"team" => mysql_insert_id()
					)));
				
				echo "<p>";	
				if ($tourney->info[teamsize] == 1)
					echo "Du bist nun f&uuml;r dieses Turnier angemeldet.";
				else
					echo "Das Team wurde angelegt.";
				echo "</p>";
			}
			
		} else {
			$f_teamname = $user_current[clan];
		}
		
		if (!$submitted || $FormErrorCount) {
			FormStart();
				FormValue("tid", $tid);
				FormValue("action", $action);
				FormValue("submitted", 1);
				
				FormElement("f_rules", "Ich habe die Regeln gelesen und akzeptiert", 1, "checkbox");
				
				if ($tourney->info[teamsize] > 1)
					FormElement("f_teamname", "Name des Teams", $f_teamname);
				
				if (($maplist || $teamtypes || $settings) && !($tourney->info[flags] & $TF_DEFMAPS)) {
					FormGroup("Standard Einstellungen");
					FormVisibleValue("", 
	"Wenn du f&uuml;r ein bestimmtes Spiel im weiteren Verlauf<br>
	keine Einstellungen angibst, werden diese Standard<br>
	Einstellungen &uuml;bernommen.");
					if ($maplist) {
						$f_map = 0;
						$size = count($maplist);
						if ($size == 1)
							$size++;
						
						FormSelectStart("f_map", "Map", $f_map, "size=".$size);
						for ($i=0; $i<count($maplist); $i++)
							FormSelectItem($maplist[$i], $i);
						FormSelectEnd();
					}
					if ($teamtypes) {
						$size = count($teamtypes);
						if ($size == 1)
							$size++;
						$f_teamtype = 0;
						
						FormSelectStart("f_teamtype", "Team Typ", $f_teamtype, "size=".$size);
						for ($i=0; $i<count($teamtypes); $i++)
							FormSelectItem($teamtypes[$i], $i);
						FormSelectEnd();
					}
					if ($settings) {
						for ($i = 0; $i < count($settings); $i++)
							FormElement("f_setting[$i]", $settings[$i], 1, "checkbox");
					}
				}
				
				FormElement("", "", "Teilnehmen", "submit");
			FormEnd();
		} else {
			//
		}
		
	// ========================================================================================
	// Team Auflösen
	// ========================================================================================
	elseif ($action == "leave_tourney"):
	
		$res = SQL_Query("SELECT * FROM tourney_teams WHERE id=$teamid");
		$team = mysql_fetch_array($res);

		if ($submitted) {
			if ($team[leader] != $user_current[id])
				LS_Error("Du kannst dieses Team nicht aufl&ouml;sen.");
				
			SQL_Query("DELETE FROM tourney_teammember WHERE team=$teamid");
			SQL_Query("DELETE FROM tourney_teams WHERE id=$teamid");
			
			if ($tourney->info[teamsize] == 1)
				echo "Du wurdest von dem Turnier abgemeldet.";
			else
				printf("Das Team <i>%s</i> wurde aufgel&ouml;st.", $team[name]);
		} else {
			if ($tourney->info[teamsize] == 1)
				echo "Willst du dich wirklich von diesem Turnier abmelden?.";
			else
				printf("Willst du das Team <i>%s</i> wirklich aufl&ouml;sen?", $team[name]);
			
			FormStart();
				FormValue("tid", $tid);
				FormValue("action", $action);
				FormValue("submitted", 1);
				FormValue("teamid", $teamid);
				
				FormElement("", "", ($tourney->info[teamsize] == 1) ? "Abmelden" : "Aufl&ouml;sen", "submit");
			FormEnd();	
		}
		
	elseif ($action == "join"):
		CheckTourneyGroup();
		if ($submitted) {
			if (!$f_rules)
				FormErrorEx("f_rules", "Du musst die Regeln dieses Turniers akzeptieren.");
			else {
				$res = SQL_Query(sprintf("SELECT * FROM tourney_teammember WHERE user=%d AND team=%d", $user_current[id], $teamid));
				$row = mysql_fetch_array($res);
				
				if (!$row)
					SQL_Query(sprintf("INSERT INTO tourney_teammember SET user=%d, team=%d", $user_current[id], $teamid));
				echo "Du wurdest als Teilnehmer des Teams hinzugef&uuml;gt.";
			}
		}
		
		if (!$submitted || $FormErrorCount) {
			FormStart();
				FormValue("tid", $tid);
				FormValue("action", $action);
				FormValue("submitted", 1);
				FormValue("teamid", $teamid);
				
				FormElement("f_rules", "Ich habe die Regelen gelesen und akzeptiert", 1, "checkbox");
				FormElement("", "", "Teilnehmen", "submit");
			FormEnd();
		} else {
			//
		}
	elseif ($action == "leave"):
		if ($submitted) {
			SQL_Query(sprintf("DELETE FROM tourney_teammember WHERE user=%d AND team=%d", $user_current[id], $teamid));
			echo "Du wurdest aus dem Team entfernt.";
		}
		
		if (!$submitted || $FormErrorCount) {
			echo "Willst du dieses Team wirklich verlassen?";
			FormStart();
				FormValue("tid", $tid);
				FormValue("action", $action);
				FormValue("submitted", 1);
				FormValue("teamid", $teamid);
				
				FormElement("", "", "Verlassen", "submit");
			FormEnd();
		} else {
			//
		}
		
	elseif ($action == "kick"):
		if ($submitted) {
			SQL_Query(sprintf("DELETE FROM tourney_teammember WHERE user=%d AND team=%d", $user, $teamid));
			echo "Der Spieler wurde aus dem Team entfernt.";
		}
		
		if (!$submitted || $FormErrorCount) {
			echo "Willst du diesen Spieler aus dem Team entfernen?";
			FormStart();
				FormValue("tid", $tid);
				FormValue("action", $action);
				FormValue("submitted", 1);
				FormValue("teamid", $teamid);
				FormValue("user", $user);
				
				FormElement("", "", "Entfernen", "submit");
			FormEnd();
		} else {
			//
		}
	
	endif;
?>
<p>
<?
	NavPrintBack();
?>
</p>
<?
	EndPage();
?>