<?
   $CSS_PATH = "../";
   $LMS_PATH = "../";
   
   require $LMS_PATH."scripts/user.inc";
   user_authorize();

	function utime()
	{
	    $time = explode(" ", microtime());
	    $usec = (double)$time[0];
	    $sec = (double)$time[1];
	    return $sec + $usec;
	}


?>
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Turniere</title>
<? require "../scripts/style.inc"; ?>
</head>

<body bgcolor="#000000" text="#77DC6E" link="#00CC00" vlink="#1A5614" alink="#77DC6E">

<?
	if (!isset($playercount))
		$playercount = 16;
	$colcount = 0;
	$matches = 1;
	while ($matches * 2 < $playercount ) {
	  $matches*=2;
	  $colcount++;
	}
	$maxmatches = $matches;
	echo "<font face=Verdana size=2><b>$playercount Spieler</b> Start Spiele: $maxmatches</font><br>";

  $extratimerounds = 2;
	$rounds = 2;
	$roundtime = 10;
	$pausetime = 10;
	$lcolcount = (($colcount * 2) + 2);
	
	$coltime = ($rounds * $roundtime) + $pausetime;
	$minutes = ($lcolcount * $coltime);
	
	for ($i=0; $i<$extratimerounds; $i++) 
		$minutes+=$coltime;

  $endtime = mktime(0,0,0,4,2,2000);
  $starttime = $endtime - ($minutes * 60);

	
	echo "<font face=Verdana size=2>
		<b>$rounds</b> Runden<br>
		<b>$roundtime</b> Minuten pro match<br>
		<b>$pausetime</b> Pause für 2 Matches<br>
		<b>$coltime</b> Minuten pro Spalte<br>
		<b>$extratimerounds</b> Runden mit doppelter Zeit<br>
		<b>".$lcolcount."</b> Spalten in der Loosers Bracket + Finale <br>
		Ben&ouml;tigte Zeit: <b>".(floor($minutes / 60))."</b> Stunden <b>".($minutes % 60)."</b> Minuten<br>
		<b>".date("H:i d.m.Y", $endtime)."</b> Endzeit<br>
		<b>".date("H:i d.m.Y", $starttime)."</b> Startzeit<br>
		</font>";
	
?>

<div align=center>
<table border=0 cellspacing=0 CELLPADDING=0 width=<? echo ((8 + 100 + 8) *(($colcount * 3) + 2)); ?> height=<? echo ($maxmatches + 2) * 48; ?>>
  <colgroup width=116 span=<? echo ($colcount * 3) + 2 ?>>
  </colgroup>
  <tr>
  <?
  
  	$currenttime = $endtime - ($coltime * 60);		// Endzeit abzüglich des Finales
    $currentcol = -($colcount * 2);
    while ($currentcol <= $colcount + 1) {
    	echo "<th>$currentcol<br>".date("H:i", $currenttime)."</th>";
    	
    	if (abs($currentcol) < $extratimerounds)
    		$thiscoltime = $coltime * 2 * 60;
    	else
    		$thiscoltime = $coltime * 60;
    	
    	if ($currentcol == 0 || $currentcol >= $colcount - 1)
    		$currenttime += $thiscoltime;
    	elseif ($currentcol > 0)
    		$currenttime += 2*$thiscoltime;
    	else
    		$currenttime -= $thiscoltime;
    	$currentcol++;
    }
  
  
  ?>
  </tr>
  <tr>
  <?
    $TDM_HEIGHT = 48;
    $TDM_SPANWIDTH = 8;
    $TDM_WIDTH = 100;
  
    $currentcol = -($colcount * 2);
    $divisor = $matches;
    $extracol = TRUE;

		$starttime=utime();


    while ($currentcol <= $colcount + 1) {
      $colplayercount =  (($maxmatches * 2) / ($divisor));
      $matchcount = ($colplayercount / 2);

    	if ($currentcol < -1 && $matchcount > 1)
    		$looserSrcRow = $matchcount / 2;
    	else
    		$looserSrcRow = $matchcount;
    
      echo "<td width=116 height=".(($maxmatches + 2) * 48).">";
/*      echo "<div align=center><b>$currentcol</b></div>";
      echo "<br>Matches: $matchcount"; */
      echo "<table border=0 cellspacing=0 CELLPADDING=0 width=116>";
      $i = 0;
        if ($currentcol < -1 || $currentcol == $colcount + 1) {
        	if ($currentcol == $colcount + 1)
        		$j = ($currentcol - 1);
        	else
        		$j = 0;
        	while ($j < abs($currentcol)) {
        		echo "<tr>
        			<td width=$TDM_SPANWIDTH height=$TDM_HEIGHT><img width=8 height=48 src=\"../Bilder/tourney/blank.gif\"></td>
        			<td width=$TDM_WIDTH height=$TDM_HEIGHT><font face=Verdana size=1><br><br><br></font></td>
        			<td width=$TDM_SPANWIDTH height=$TDM_HEIGHT><img width=8 height=48 src=\"../Bilder/tourney/blank.gif\"></td>
        		</tr>\n";
        		$j++;
        	}
        }
      while ($i < $matchcount) {
      	echo "<tr>";
      	
     		// Linke Seite des Matches
     		echo "<td width=$TDM_SPANWIDTH height=$TDM_HEIGHT><img width=8 height=48 src=\"../Bilder/tourney/";
     		if ($currentcol <= 0) {
     		  if (!($i % 2)  || (!$extracol && $currentcol < 0))
     		  	echo "top_right";
     		  else
     		    echo "bottom_right";
     		} else 
     			echo "middle";
  		  echo ".gif\"></td>";
      	
      	// Match Selber
      	echo "<td width=$TDM_WIDTH height=$TDM_HEIGHT bgcolor=";
      	if ($extracol || ($currentcol == 0 && ($i % 2)))
      		echo "#151515";
      	else
      		echo "#202020";
      	echo " align=center width=100><font face=Verdana size=1>";
      	if ($currentcol == -1)
      		echo "<font color=#A0A0A0>Verlierer ".(($i * 2) + 1)."</font>";
      	elseif ($currentcol == 1)
      		echo "<font color=#A0A0A0>Gewinner ".(($i * 2) + 1)."</font>";
      	elseif ($currentcol > 1 && $currentcol <= $colcount)
      		echo "<font color=#A0A0A0>Gewinner ".chr($currentcol + 63).(($i * 2) + 1)."</font>";
      	elseif ($currentcol == 0)
      		echo "<font color=#77DC6E>Spieler ".(($i * 2) + 1)."</font>";
      	else
      		echo "<font color=#A0A0A0>???</font>";
      	echo "<br><font size=1 color=white>vs</font><br>";
      	if ($currentcol == -1)
      		echo "<font color=#A0A0A0>Verlierer ".(($i * 2) + 2)."</font>";
      	elseif ($currentcol == 1)
      		echo "<font color=#A0A0A0>Gewinner ".(($i * 2) + 2)."</font>";
      	elseif ($currentcol > 1 && $currentcol <= $colcount)
      		echo "<font color=#A0A0A0>Gewinner ".chr($currentcol + 63).(($i * 2) + 2)."</font>";
      	elseif ($currentcol == 0)
      		echo "<font color=#77DC6E>Spieler ".(($i * 2) + 2)."</font>";
      	else
      		echo "<font color=#A0A0A0>???</font>";
      	echo "</font></td>";

				// Rechte Seite des Matches
     		echo "<td width=$TDM_SPANWIDTH height=$TDM_HEIGHT><img width=8 height=48 src=\"../Bilder/tourney/";
     		if ($currentcol >= 0) {
     		  if ($i % 2)
     		  	echo "bottom_left";
     		  else
     		    echo "top_left";
     		} else 
     			echo "middle";
  		  echo ".gif\"></td>";

      	echo "</tr>";
      	$i++;
        if ($i > 0) {
          $dest = $divisor;
          if ($i >= $matchcount)
          	$dest = 2;
          $j = 1;
          while ($j < abs($dest)) {
        		echo "<tr>";
       		  echo "<td width=$TDM_SPANWIDTH height=$TDM_HEIGHT><img width=8 height=48 src=\"../Bilder/tourney/";
       		  $text = "<br><br><br>";
        		if ($currentcol < 0 && ($i % 2 || !$extracol) ) {
        			if (!$extracol) {
        				if ($j == 1) {
        		  		echo "bottom_right";
//        		  		$text = "<br>&nbsp;&nbsp;Verlierer ".chr(abs($currentcol / 2) + 65).($matchcount - $i + 1)."<br><br>";
        		  		$text = "<br>&nbsp;&nbsp;Verlierer ".chr(abs($currentcol / 2) + 65).($looserSrcRow)."<br><br>";
        		  		$looserSrcRow--;
        		  		if ($looserSrcRow == 0)
        		  			$looserSrcRow = $matchcount;
        		  	}
        		  	else
        		  		echo "blank";
        		  }
        		  else {
        		  	if ($currentcol == -($colcount * 2)) {
        		  		echo "bottom_right";
        		  		$text = "<br>&nbsp;&nbsp;Zum Finale<br><br>";
        		  	}
        		  	else
        		  		echo "right";
        		  }
        		}
        		else 
        		  echo "blank";
        		if ($currentcol > 0 && $j == 1) {
        			$text = "<div align=right>".chr($currentcol + 64).$i."<br><br><br></div>";
        			if ($currentcol == $colcount)
        		  		$text = "<div align=right><br>Gewinner der&nbsp;&nbsp;<br>Loosers Bracket<br></div>";
        			if ($currentcol > $colcount)
        		  		$text = "<div align=right><br>Gewinner des Turniers&nbsp;&nbsp;<br><br></div>";
        		}
       		  echo ".gif\"></td>";
        		echo "<td><font face=\"Verdana\" size=1 color=#A0A0A0>$text</font></td>";
        		echo "<td><img width=8 height=48 src=\"../Bilder/tourney/";
        		if ($currentcol >= 0 && ($i % 2)) {
        			if ($currentcol >= $colcount)
        				echo "bottom_left";
        			else
        		  	echo "left";
        		}
        		else
        		  echo "blank";
        		echo ".gif\"></td>";
        		echo "</tr>";
        		$j++;
        	}
        }
      }
      
      echo "</table>";
      
      echo "</td>";
      if (!$extracol) {
	      if ($currentcol < 0)
	      	$divisor /= 2;
	      else
	      	$divisor *= 2;
	    }
      $currentcol++;
      if ($currentcol < 0)
     		$extracol = !$extracol;
     	else
     		$extracol = FALSE;
    }

  
  ?>
  </tr>
</table>
</div>

<?
printf("\rDone, took %.2f seconds.\n", ($idle_while=utime()-$starttime));
?>

</body>

</html>
